### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by newtongamajr** [Flagstudio/nova-actions-left#1]
Hi, 
I've installed nova-actions-left as specified by your instruction but my nova actions still on the same right position. Everything seems to be installed, from my searches on my Nova project. 
Any suggestion? Thanks in advance!

**Comment by vasishakd** [comment]
What version of nova are you using?

**Comment by newtongamajr** [comment]
My Nova version is 2.9.2

**Comment by nachiomdq** [comment]
> Hi,
> I've installed nova-actions-left as specified by your instruction but my nova actions still on the same right position. Everything seems to be installed, from my searches on my Nova project.
> Any suggestion? Thanks in advance!

I had the same problem, I have refreshed the cache and it works without problems.

**Comment by yarbala** [comment]
I have latest nova (3.16.3) - and cache clearing dose not helps

**Comment by vasishakd** [comment]
> I have latest nova (3.16.3) - and cache clearing dose not helps

This package works by replacing ResourceTableRow and ResourceTable vue components. If u have some another package that replacing it too, this package won't work
